# TravisCI buid for Project TicTacToe (Thanks to https://github.com/nielsAD/travis-lazarus)
# License: MIT

language: generic
sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - LAZ_VER=2.0.10 # Use specific (binary) release

matrix:
  include:
    - os: linux
      env: LAZ_VER=2.0.10 LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=2.0.10  LAZ_ENV='' LAZ_OPT="--os=linux --cpu=x86_64"


before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &

install:
  # Install prerequisites (fpc/lazarus/wine/qemu)
  - python ./.travis.install.py

script:
  - lazbuild $LAZ_OPT TicTacToe.lpi                     # Build TicTacToe project to verify it compiles

